version: '3'

volumes:
  piggybank_postgres_data:


services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=piggybank
    volumes:
      - piggybank_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
